@startuml Diagrama de Clases: AdoptAR

!define MyFontColor #000000
!define MyBorderColor #800080
!define MyBackgroundColor #E6E6FA
!define MyArrowColor #800080
!define MyPackageColor #DDDDDD

skinparam defaultFontName Arial
skinparam DefaultFontSize 13
skinparam Linetype ortho
skinparam Arrowcolor MyArrowColor
skinparam ArrowThickness 2
skinparam Classbordercolor MyBorderColor
skinparam ClassBorderThickness 2
skinparam ClassBackgroundColor MyBackgroundColor
skinparam Shadowing true
skinparam GroupInheritance 1
skinparam NoteBackgroundColor yellow
skinparam NoteBorderThickness 2
skinparam PackageBackgroundColor MyPackageColor

class App {

  -Usuarios: Usuario[]
  -Mascotas: Mascota[] 
  -Publicaciones: Publicacion[]
  -Visitas: Visita[]
  -Notificador : Notificador

  + listar_mascotas() 
  + listar_turnos()
  + *otras_funciones()*

}

Abstract class Usuario {
  - id: Integer /' [PK] '/
  - nombre: String
  - email: String
  - telefono: Integer
  
  + agendar_visita()


  /' + realizar_donacion() '/
}

class Administrador extends Usuario {

}

class Visitante extends Usuario {
  
}

class Publicador extends Usuario {

}

class Notificador {

}

Abstract class Mascota {
  - id: Integer /' [PK] '/
  - nombre: String
  - especie: String
  - imagenes: Imagen[]
  - ubicacion_de_transito: String
  - edad: Integer
  - adoptado: Boolean
}

class Perro extends Mascota{
}

class Gato extends Mascota {

}
  
class Visita {
  - id: Integer /' [PK] '/
  - prioridad: Integer
  - estado: EstadoVisita
  - formulario: FormularioVisita
}

class Publicacion {
  - id: Integer /' [PK] '/
  - mascota_id: Integer /' [FK] '/
  - publicador_id: Integer /' [FK] '/
  - fecha_publicacion: Date
  - ubicacion: String
  - descripcion: String
  - estado: EstadoPublicacion
  
}

class FormularioVisita { 
  - id: Integer /' [PK] '/
  - publicacion_id: Integer /' [FK] '/
  - usuario_id: Integer /' [FK] '/
  - fecha_visita: Date
}

/' En caso de implementar donaciones
class Donacion {
  - usuario_id: Integer /' [FK] ' /
  - mascota_id: Integer /' [FK] ' /
  - tipo_donacion: String
  - importe_donacion: Number
  - items_seleccion: ArrayList []
  - lista_necesidades: ArrayList [] 
}
 '/

interface Abm {
  /' usuarios,mascotas y visitas '/
  + agregar()
  + eliminar()
  + modificar()
}

ENUM EstadoVisita {
  AGENDADO
  CONFIRMADO
  RECHAZADO
}

ENUM EstadoPublicacion {
  ACTIVA
  INACTIVA
}

/' Relaciones '/
 ''Donacion o-r- Usuario

Usuario *-- Visita  

App *-- Usuario  /' : "tiene" '/
App *-- Notificador  /' : "tiene" '/
App *-- Mascota  /' : "tiene" '/
App *-- Publicacion  /' : "tiene" '/
App *-- Visita  /' : "tiene" '/
App .right.> Abm   /' : "usa" '/
Visita ..> EstadoVisita /' : "usa" '/
Visita ..> FormularioVisita  /' : "usa" '/
Publicacion .left.> EstadoPublicacion /' : "usa" '/

Administrador ..> Publicacion /' : "usa" '/
Publicador ..> Publicacion /' : "usa" '/

/' Cardinalidad '/

Usuario "1" -left-> "0..*  " Visita /' : "realiza" '/


''Usuario "1" --> "0..*" Donacion /' : "realiza" '/

@enduml
