@startuml Adoptar
/'
!define MyFontColor #000000
!define MyBorderColor #800080
!define MyBackgroundColor #E6E6FA
!define MyArrowColor #800080
!define MyPackageColor #DDDDDD

skinparam defaultFontName Arial
skinparam DefaultFontSize 13
skinparam Linetype ortho
skinparam Arrowcolor MyArrowColor
skinparam ArrowThickness 2
skinparam Classbordercolor MyBorderColor
skinparam ClassBorderThickness 2
skinparam ClassBackgroundColor MyBackgroundColor
skinparam Shadowing true
skinparam GroupInheritance 1
skinparam NoteBackgroundColor yellow
skinparam NoteBorderThickness 2
skinparam PackageBackgroundColor MyPackageColor
'/
skinparam Linetype ortho

interface IAdoptar {
    + MostrarPublicaciones()
    + Vistar()
    + IniciarSesion()
    + CerrarSesion() 
}

class Adoptar implements IAdoptar {
    - usuarios: usuario[] 
    - publicaciones: Publicacion[]
}

abstract class Usuario {
    - id: Integer
    - nombre: string
    - email: string
    - contrasenia: string
}

/' Administrador '/

class Administrador extends Usuario {
    - usuarios: Usuario[]
    - publicadores: Publicador[]
}

/' Gestor Publicaciones '/

class Publicador extends Usuario{
    + Publicar(publicacion:Publicacion)
    + BorrarPublicacion(publicacion:Publicacion)
    + EditarPublicacion(publicacion:Publicacion)
}

class Publicacion{
    - id: Integer
    - publicador: Publicador
    - mascota:Mascota
    - fecha:Date
    - estado:ESTADO_PUBLICACION
    - fotos:Imagen[4]
    - ubicacion: string
    - contacto: string
}

enum ESTADO_PUBLICACION{
    ABIERTA;
    CERRADA;
}

class Mascota{
    - id:Integer
    - especie:ESPECIE
    - raza:RAZA
    - edad:Integer
    - tamanio:TAMANIO
    - condicion:CONDICION
}

enum ESPECIE{
    GATO;
    PERRO;
}

enum RAZA{
    SINRAZA;
    DOGO;
}

enum TAMANIO{
    GRANDE;
    MEDIANO;
    CHICO;
}

enum CONDICION{
    TRANSITO;
    REFUGIO;
}

/' Gestor Visitas'/

class Visitante {
    - nombre: string
    - email: string
}

class Visita{
    - disponibilidad: Date
    - descripcion: string
    - visitante:Visitante
    - publicacion:Publicacion
    - estado: ESTADO_VISITA
}

enum ESTADO_VISITA{
    PENDIENTE
    APROBADO
    RECHAZADO
}

/' relaciones'/

Adoptar "1"--* "N  " Usuario
Adoptar "1"--*"N  " Publicacion
Administrador "1"--*"N  " Publicador
Publicacion "1"--*"1" Publicador
Publicacion "1"--*"1  " Mascota
Publicacion --* ESTADO_PUBLICACION
Mascota -- ESPECIE
Mascota -- RAZA
Mascota -- TAMANIO
Mascota -- CONDICION
Visita "1"--*"1" Visitante
Visita "1"--*"1" Publicacion
Visita --* ESTADO_VISITA

@enduml