@startuml caso de uso 1

'caso de uso 1 
'Usuario publicador (registrado y autenticado):
'Ver Registrarse o Iniciar sesión o Crear publicación

actor "Usuario publicador" as Publicador

rectangle "web AdoptAR" {
    
    (Registrarse) as Registrarse
    (Iniciar sesión) as IniciarSesion
    (Crear publicación) as CrearPublicacion
}

Publicador --> Registrarse
Publicador --> IniciarSesion
IniciarSesion --> CrearPublicacion

@enduml
